### ISSUE TITLE
replace componentWillReceiveProps

### ISSUE THREAD

**Issue by bigwillch** [jaanauati/react-dfp#105]
Just on observation when going through the code that `componentWillReceiveProps` is being deprecated and so should be replaced at some point

https://github.com/jaanauati/react-dfp/blob/master/js/adslot.js#L63

https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by jaanauati** [comment]
thanks again @bigwillch!, this have been fixed in v0.9.3 (turned out that the code was no longer needed).
