### ISSUE TITLE
Implementing activity tags

### ISSUE THREAD

**Issue by mtebele** [jaanauati/react-dfp#129]
Hi! I'm trying to implement this code, but I have no idea how to do it with this lib:

```
<script type='text/javascript'>
var axel = Math.random()+"";
var a = axel * 10000000000000;
document.write('<img src="https://pubads.g.doubleclick.net/activity;xsp=4453085;ord='+ a +'?" width=1 height=1 border=0>');
</script>

<noscript>
<img src="https://pubads.g.doubleclick.net/activity;xsp=4453085;ord=1?" width=1 height=1 border=0>
</noscript>
```

It refers to the following article: https://support.google.com/admanager/answer/2499318?hl=en

Any help would be great.

Thanks!

**Comment by jaanauati** [comment]
Hi, I never set this up, but according the documentation it sounds like u should only append the `<img />` tag to the document's body and dpf should do the rest for you, i'm guessing you could append the node even using react
```
<img src={`https://pubads.g.doubleclick.net/activity;xsp=4453085;ord=${ord}?"`} />
```
Hope this helps.
thanks.
