### ISSUE TITLE
Support for lazy load

### ISSUE THREAD

**Issue by eagle1000** [jaanauati/react-dfp#130]
Hello,

Does react-dfp support lazy loading of ads as shown in this gpt sample? 

https://support.google.com/admanager/answer/4578089#lazyloading

If so, could you please provide an example as to how to use this feature?  Thank you!

**Comment by jaanauati** [comment]
Hi, react-dfp does not have support for that api yet, but, on the other hand u should be able to adress this feature just using any of the available lazy load components, like react-lazy-load, just wrap your adSlot with the lazy load component this way: 

<LazyLoad ....> <AdSlot .../> </LazyLoad>

Let me know if u have issues, I’ll try to add an example to the documentation site in the following days.
Thanks

**Comment by eagle1000** [comment]
Hi, thank you for the response.  I will play around with using a lazy load component this weekend and share the results.  My only concern with doing this is that google does warn that other forms of implementation for lazy load may trigger multiple ad requests that do not trigger a creative and lead to a lower viewability rate.   https://support.google.com/admanager/answer/6199883?hl=en

**Comment by jaanauati** [comment]
@eagle1000 fyi, I've just pushed v0.11.0, this version adds support for the gpt's lazy load api.
Also made updates to the documentation site, you can find couple of examples here:
- http://react-dfp.tk/dfpslotsprovider/lazyload/ (using DFPSlotsProvided, this is the recommended way)
- http://react-dfp.tk/dfpmanager/configurelazyload/ (via DFPManager.js, useful in case u don't use DFPSlotsProvided)

please take a look and let me know if u have questions.
thanks.

**Comment by eagle1000** [comment]
Hi, I cannot seem to get the lazy load to work.  For simplicity, I am calling the AdSlot directly on the page with DFP manager.  I have also tried using DFPSLotsProvider, but that does not seem to work either.  I have an ad well down below the fold, out of the viewport and yet it always fetches and renders when the page is loaded.  I am trying to have it render when the AdSlot comes into the viewport.
Here is a sample of my code:

`class Home extends Component {
    componentDidMount() {
        DFPManager.configureSingleRequest(false);
        DFPManager.configureLazyLoad(true, {
            fetchMarginPercent: 0,
            renderMarginPercent: 0,
            mobileScaling: 1.0,
        });
        DFPManager.load();
    }
    render() {
        return (
            <div>
              <DetectAdBlock/>
              <AdSlot
                dfpNetworkId={"999999999"}
                adUnit={"leaderboard"}
                sizes={[[970, 250], [970, 90], [728, 90], [468, 60], [320, 100], [320, 50]]}
                sizeMapping={[{ viewport: [1024, 0], sizes: [[728, 90], [970, 90], [970, 250]] }, { viewport: [768, 0], sizes: [[728, 90], [468, 60]] }, { viewport: [520, 0], sizes: [[468, 60], [320, 100], [320, 50]] }, { viewport: [0, 0], sizes: [[320, 100], [320, 50]] }]}
              />
              <HomeHeader />
              <HomeThumbnails />
              <TextBody/>   
              <ImageSlider />
              <QuestionField />    
              <AdSlot 
                dfpNetworkId={"999999999"}
                adUnit={"BottomMPU"} 
                sizes={[ [970, 250], [970, 90], [728, 90], [468, 60], [300, 250], [336, 280], [320, 100], [320, 50] ]} 
                sizeMapping={[{ viewport: [1200, 0], sizes: [[336, 280], [300, 250]] }, { viewport: [1024, 0], sizes: [ [970, 90], [970, 250], [728, 90] ] }, { viewport: [768, 0], sizes: [ [468, 60], [728, 90] ] }, { viewport: [576, 0], sizes: [ [468, 60], [300, 250], [320, 100], [320, 50], [336, 280]] }, { viewport: [360, 0], sizes: [ [300, 250], [320, 100], [320, 50], [336, 280]] }, { viewport: [0, 0], sizes: [ [300, 250], [320, 100], [320, 50]] } ]}
              />   
            </div>
        );
    }
}
export default withRouter(Home);`

**Comment by jaanauati** [comment]
@eagle1000 have u finally figured this out?, I can see it working at: http://react-dfp.ml/dfpslotsprovider/lazyload/.

I see that the ad requests `ads?....` are only fired (network panel) when i scroll down and I reach the area where the Ad Slots are located.

Let me know if it still does not work for u.

**Comment by neolele** [comment]
Hi,
I need to enable lazyloading just for few AdSlots but it see it's configurable at DFPSlotsProvider level. is there any way to do it without other implementations?

thank you very much
Regards

**Comment by neolele** [comment]
Hi,
I got problems enabling lazyLoading too, I'm using the <DFPSlotsProvider lazyLoad> approach.
with onSlotRender on AdSlot I'm console logging render event even when adslot is not viewable on page load. besides, I'd need to enable lazyLoading only on some adslots, not all. is it possible?

thank you
regards

**Comment by jaanauati** [comment]
Hi unfortunately the gpt api does support such feature, on the other hand,
if u want to lazy-load only some ads you can always use any of the many
lazy load components available in npm (react-lazy-load, etc), in this case
you can just declare your ad slots inside of the lazy load component, if
you are working with the <DFPSlotsProvider> your ads will show up as soon
as the are is in the viewport (according config you pass to
react-lazy-load).
Example:

<DFPSlotsProvide ...>
   ....
    ....
     <AdSlot .... />
    ...
    <LazyLoad ...> <AdSlot ... /> </LazyLoad>
    ...
    <LazyLoad> <AdSlot .... /> </LazyLoad>
  ....
</DFPSlotsProvider>

Notice that in this example the last two ads are lazy loaded.

https://github.com/twobin/react-lazyload

Let me know if you still have issues.

Thanks.
