### ISSUE TITLE
AdSense 403

### ISSUE THREAD

**Issue by play75010** [jaanauati/react-dfp#131]
Hello.

Obviously, some of you have succeeded in getting AdSense through DFP calls. 

I have implemented an AdSense campaign in DFP (maybe there is a better way of doing this). 

When I call the <AdSlot>, I get a correct Ad if DFP returns an ad which is not AdSense but I get a 403 if it returns an AdSense Ad. I've tried to pass "page_url" with the URL of the website where ads are currently displayed but with no luck. 

Any help would be greatly appreciated.

**Comment by eagle1000** [comment]
Hi,

I am experiencing similar troubles but I am not sure it is entirely an AdSense issue.  I notice that roughly 1/3 of my ad units are not displaying a creative.  Using publisher console to debug, I do see that there is indeed a "winning line item".  However, the overlay status of the ad unit is "not displayed".  

Using the publisher console, when I open the creative in a new window the creative is once again not displayed.  In the console, this is where is see the 403 error message.  Additionally, I also receive a message regarding preload  warnings which I previously referenced in Issue #88 but have not received any response for.

I too cannot figure out why ads are not displaying even though they are serving according to Ad Manager.
![adsense1](https://user-images.githubusercontent.com/30674397/55581279-0d76d500-56e2-11e9-9aad-e33ed4df07ba.JPG)
![adsense2](https://user-images.githubusercontent.com/30674397/55581280-0e0f6b80-56e2-11e9-8857-5352533d680a.JPG)

**Comment by jaanauati** [comment]
Hi,

> Using the publisher console, when I open the creative in a new window the creative is once again not displayed

Is the browser console showing 403s in this case also?. In any case, it would be great If u guys can share a snippet of your code so I can try to review and help.

Thank you.

**Comment by jaanauati** [comment]
@eagle1000 are u still having issues?, if your ads are not loading 1/3 perhaps you are having the same issue as reported here: https://github.com/jaanauati/react-dfp/issues/149, pls take a look and let me know if the workaround provided in that ticket also fixes your issues.

**Comment by eagle1000** [comment]
@jaanauati I keep recieving the following error message when trying the fix from #149.  

Unhandled Rejection (TypeError): googletag.pubads is not a function

I am calling calling DFP manager in componentDidMount with the suggested code
`    DFPManager.getGoogletag().then(googletag =>
      googletag.pubads().updateCorrelator()
    );`

To the Adslot:
`       <AdSlot
                  dfpNetworkId={"XXXXXXXXX"}
                  adUnit={"leaderboard"}
                  sizes={[[970, 250], [970, 90], [728, 90], [468, 60], [320, 100], [320, 50]]}
        />`
Previously, I was just calling `DFPManager.load();` in componentDidMount.  Is there something different to have `googletag.pubads()` to be recognized?

**Comment by jaanauati** [comment]
@eagle1000 are u using AdSlot in combination with DFPSlotsProvider?, if not you will need to add a manual call to DFMManager.load(), could you please share a snippet w your code? (Code sandbox would be great!). Thank you!
