### ISSUE TITLE
Passing down AdSlot to Child Components

### ISSUE THREAD

**Issue by oyilmaztekin** [jaanauati/react-dfp#134]
Using `AdSlot` in a child component causes a problem and it affects all `AdSlot` components all around the page.  Is there a way to pass down `AdSlot` to the child components as a prop or defining `AdSlot` into child components without declaring `DFPSlotsProvider`?

`DFPSlotsProvider` already declared in the parent component and also we can use only one `DFPSlotsProvider` into the page. 

```javascript
 <DFPSlotsProvider dfpNetworkId={adNetworkID}>
        <AdSlot
          sizes={[[970, 250]]}
          adUnit={"AnasayfaMastHead"}
          slotId="anasayfaMastHead"
        />
        <AdSlot
          sizes={[[160, 600], [120, 600]]}
          adUnit={"anasayfa_sol1"}
          slotId="anasayfa_sol"
        />

        <Block type="main">
              <Article
                title={title}
                desc={description}
                cat={breadcrumbs.cat.title}
                catUrl={breadcrumbs.cat.url}
                className="main-article"
                cover={haber_gorsel[0]._id}
                isSSR={true}
                content={haber_metni}
                slot={ { <AdSlot /> } } // or inside this component
              >
                <CardManager
                  dataset="cat-gundem"
                  limit={2}
                  vertical={true}
                  cardBg="#282841"
                  className="section-cards__sag-manset-yani"
                  imgClassName="nomargin"
                  border="#ffa200"
                  width={303}
                  lineHeight="24"
                  textColor="#fff"
                  slot={ { <AdSlot /> } } // or inside this component
                />
                <AdSlot
                  sizes={[[970, 120]]}
                  adUnit={"HaberDetay_970x250"}
                  slotId="HaberDetay_970x250"
                />
              </Article>
            </Block>
      </DFPSlotsProvider>
```

**Comment by jaanauati** [comment]
Hi,
> `child component causes a problem and it affects `
could u please clarify a little bit on what the problem is (stacktrace, behavior ,etc), 

on the other hand, at first glance your code seems like right, the only thing u might be doing wrong is passing a fixed value to the `slotId` prop, perhaps this is not clear in the documentation, but reusing the same value leads to bugs (especially after refreshing components). If u don't pass any value react-dfp will compute a value for it behind the scenes/automatically, Could u please try w removing that prop?
