### ISSUE TITLE
AdSlots keep the initial `personalizedAds` prop value after load

### ISSUE THREAD

**Issue by apascal** [jaanauati/react-dfp#135]
We have a `DFPSlotsProvider` component with a `personalizedAds` prop, which can change over time.

The issue is that all ads on the page are rendered with the initial `personalizedAds` prop value.
This is normal for the first call, but after the property changes - and `DFPSlotsProvider` is re-rendered - all subsequent DFP calls still include this initial `personalizedAds` prop value.

Subsequent calls include Ads that where not loaded because of lazyload, or refreshed ads.

We have tried to manually trigger `DFPManager.configurePersonalizedAds()` on prop change, but it doesn't change the fact that all `AdSlot`s are already `load`ed with this `personalizedAds` value.

Is is possible that on ad call, the current `personalizedAds` prop value is evaluated dynamically?

The current workaround is to render `DFPSlotsProvider` without `autoLoad`, and wait for `personalizedAds` to be defined, but it makes the component way too smart and prone to errors.

**Comment by jaanauati** [comment]
Hi, updating props on the provider is still not supported (https://github.com/jaanauati/react-dfp/pull/136), one way I think you should be able to deal w this is: 1) call `configurePersonalizedAds(false)` and, 2) then refresh the ads in the page:
```
DFPManager.configurePersonalizedAds(false);
DFPManager.refresh();
```
Could u please give this a try and let me know if it works?

Thanks.

**Comment by apascal** [comment]
Hi @jaanauati, thank you for your quick response. Glad to see #136 is a work in progress, as this seems to be part of the problem.
Refreshing the ads manually does work, however it has an impact on the ad calls and the ads visibility: every ad is likely to be called twice on page load (in a GDPR use case the user consent is asynchronous).

Just to make sure that this is the same problem: I am surprised that delayed lazyloaded ads have the `personalizedAds` value as the initial one of the provider when they are called, whereas on refresh their value is updated.

```
// pseudo code with prop value coming from user preference
componentDidUpdate() {
  DFPManager.configurePersonalizedAds(false);
}

render() {
    return (
      <DFPSlotsProvider
        lazyLoad
        personalizedAds
        singleRequest={false}
        dfpNetworkId="####"
      >
          <AdSlot adUnit="visible_on_first_render" />
          <AdSlot adUnit="invisible_on_first_render" />
      </DFPSlotsProvider>
    );
}
```
-> after the `componentDidUpdate()`, when the user scrolls and the second `AdSlot` enters viewport and is loaded, the `personalizedAds` is `true`.

**Comment by jaanauati** [comment]
Sorry about the delay,
```
-> after the componentDidUpdate(), when the user scrolls and the second AdSlot enters viewport and is loaded, the personalizedAds is true.
```
This is expected, the props u see are those you passed to `<DFPSlotsProvider>` on the other hand, under the scenes DFPManage will hold the right value (the one u passed manually when componentDidMount was invoked).

Also, for this example to work in the way you expect you you should pass the prop autoLoad=false, so that DFPSlotsPropvider does not call DFPManager.load() when it gets mounted. Please see http://react-dfp.ml/dfpslotsprovider/autoload/.

Let me know if this works for u.

thanks

**Comment by jaanauati** [comment]
@apascal i'm closing this out, feel free to reopen if u still have issues. thanks.
