### ISSUE TITLE
Lazy Loading is not working

### ISSUE THREAD

**Issue by marcosvlehmkuhl** [jaanauati/react-dfp#193]
Lazy loading is not working.
I made a codesandbox to show on [https://codesandbox.io/s/react-dfp-lazy-loading-pmk2q](https://codesandbox.io/s/react-dfp-lazy-loading-pmk2q?file=/src/App.js).

**Comment by jaanauati** [comment]
@marcosvlehmkuhl v0.17.3 has been published to the npm registry. 

thank you!
