### ISSUE TITLE
Stop Cookies being set on the page through setCookieOptions

### ISSUE THREAD

**Issue by daraclare** [jaanauati/react-dfp#199]
Hello, and, thanks for a really useful library 😄 

This may be a feature request. We're trying to comply with some upcoming EU regulations and we need to be able to turn off cookies completely, while still showing ad — is it possible to allow for the `setCookieOptions(1)` to be set through the `DFPSlotsProvider`, similar to the way we can add `personalizedAds={false}` (this doesn't turn off cookies unfortunately).
More about setCookieOptions on the Google dev docs: https://developers.google.com/doubleclick-gpt/reference#googletag.pubadsservice-setcookieoptionsoptions

**Comment by daraclare** [comment]
I hope the PR above allows for this :)

**Comment by jaanauati** [comment]
react-dfp@0.18.0 has been published to npm, please let me know if u find any issues, THANKS!
