### ISSUE TITLE
Unsupported Engine

### ISSUE THREAD

**Issue by jlafosse** [jaanauati/react-dfp#212]
When doing an npm install, I am receiving an unsupported engine from react-dfp. Is there any reason that the node version in the react-dfp engines definition cannot be updated?  Thanks.

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-dfp@0.20.0',
npm WARN EBADENGINE   required: { node: '<=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.21.0', npm: '7.6.0' }
npm WARN EBADENGINE }

**Comment by jaanauati** [comment]
Oh good catch, I don't see any reasons on why that property can not updated. I'll try to make a fix in the following days. Thank you!

**Comment by jlafosse** [comment]
Great, thanks!

**Comment by jaanauati** [comment]
@jlafosse I just pushed a fix attempt. For some weird reason these warnings were not showing up in my local. Please give it a try and let me know in case u still find issues. Thanks.

**Comment by jlafosse** [comment]
That did the trick, thanks!
