### ISSUE TITLE
Auto-generated slot IDs are not always unique

### ISSUE THREAD

**Issue by mgoggin** [jaanauati/react-dfp#22]
I have 4 `<AdSlot />`s next to each other and when each one generates its own slot ID, quite frequently, the same ID gets generated for more than one `<AdSlot />`. This causes the slots to fail to register with `DFPManager` which causes those slots to fail to load at all.

I've worked around this issue by manually specifying `slotId` for each `<AdSlot />`.

**Comment by jaanauati** [comment]
yeah, there is actually a fix for this issue in https://github.com/jaanauati/react-dfp/pull/21; review process is currently in progress.

Thanks!.

**Comment by mgoggin** [comment]
Oh awesome. Guess I should have read through that issue a little more thoroughly.

**Comment by jaanauati** [comment]
fix just pushed to npm @mgoggin so i'm closing this one, please let me know if something goes wrong.
thanks.
