### ISSUE TITLE
Missing autoReload type on IDFPSlotsProviderProps.

### ISSUE THREAD

**Issue by azizcoban** [jaanauati/react-dfp#237]
I was trying to apply autoReload functionality which is mentioned here: https://react-dfp.surge.sh/dfpslotsprovider/autoreload/
But then typescript warned me like
<img width="535" alt="Screen Shot 2022-06-06 at 18 02 28" src="https://user-images.githubusercontent.com/29438839/172187848-f8281f69-b481-43cb-8232-b95db1f6ec74.png">
 
Then I checked the `IDFPSlotsProviderProps` but interestingly there is no `autoReload` prop type defined even if there is a use case like that in documentation.

**Comment by jaanauati** [comment]
Hi, `react-dfp` does not have any typescript support yet. Not sure where `IDFPSlotsProviderProps` comes from, I wonder if it is some sort of custom interface definition declared in your project?
