### ISSUE TITLE
Lots of postMessage in not a function error in mobile Safari

### ISSUE THREAD

**Issue by coluccini** [jaanauati/react-dfp#38]
Hi,
I've started to show dpf in my web a few days ago using react-dfp and I'm seeing a bunch of `postMessage in not a function` error in my logs. All error appears to be coming from the adsense script and almost all of them comes from mobile Safari, so I don't think is a react-dfp issue, but maybe someone around here can know why are this error happening or if there is something I can do to prevent them from happening.

Thanks for this amazing module by the way!

**Comment by jaanauati** [comment]
@coluccini i know this ticket is a little old, were u able to answer your question? given that it does not seem to bug i'm closing it out, feel free to reopen if it's giving u issues. thanks
