### ISSUE TITLE
How to set page_url in react-dfp? 

### ISSUE THREAD

**Issue by enteeee** [jaanauati/react-dfp#44]
https://developers.google.com/doubleclick-gpt/adsense_attributes

`googletag.pubads().set("page_url", "URL"); `

**Comment by jaanauati** [comment]
hey, this is not supported by the react-dfp interface (just yet), but on the other hand, the `DFPManager` object allows you to play with the googletag API, so you could accomplish this in the following way:
```
import { DFPManager } from 'react-dfp';
DFPManager.getGoogletag().then(
  googletag => googletag.cmd.push( () => googletag.pubads().set('page_url', 'URL') )
);
```

Just make sure this is executed before the components are mounted.

for the record, i'm planning to add support for this feature in the Components interface (passing component props), so hopefully will be implemented in the next few weeks.

**Comment by jaanauati** [comment]
Just merged this pull request: https://github.com/jaanauati/react-dfp/pull/45. The new interface prop (`adSenseAttributes`) allow u to pass adSense attributes in the following manner: 
``` <DFPSlotsProvider collapseEmptyDivs adSenseAttributes={{ page_url: 'www.site.com' }} dfpNetworkId={networkId} adUnit={'test'}>
      <div>
        <div className="ad-example-728x90">
          <AdSlot sizes={[[728, 90]]} adSenseAttributes={{ adsense_link_color: '#00FFFF', adsense_background_color: '#000000' }} />
          <Highlight>
            {'<AdSlot sizes={[[728, 90]]}/>'}
          </Highlight>
        </div>
        <div className="ad-example-300x250">
          <AdSlot sizes={[[300, 250]]} adSenseAttributes={{ adsense_ad_types: 'text_image' }} />
          <Highlight>
            {'<AdSlot sizes={[[300, 250]]}/>'}
          </Highlight>
        </div>
      </div>
```
thanks
