### ISSUE TITLE
collapseEmptyDivs not working?

### ISSUE THREAD

**Issue by evrenakar** [jaanauati/react-dfp#46]
collapseEmptyDivs not working. Help me please?

`<DFPSlotsProvider dfpNetworkId='4519939' collapseEmptyDivs={true}>
                                <AdSlot adUnit={"4519939/deneme_300x250"} sizes={[[300, 250]]}/>
                            </DFPSlotsProvider>
                            <DFPSlotsProvider dfpNetworkId='4519939' collapseEmptyDivs={true}>
                                <AdSlot adUnit={"4519939/deneme_300x600"} sizes={[[300, 600]]} />
                            </DFPSlotsProvider>
                            <DFPSlotsProvider dfpNetworkId='4519939' collapseEmptyDivs={true}>
                                <AdSlot adUnit={"4519939/deneme_300x250_2"} sizes={[[300, 250]]} />
                            </DFPSlotsProvider>`

**Comment by jaanauati** [comment]
hi!, i believe your problem might be the fact that you are declaring more than one `<DFPSlotsProvider>` in the page, this component has no visual effects, and it is designed to be to pass dfp global options (such as id, collapseEmptyDivs flag, etc) so you should only declare one instance of it (as top as possible). Take a look at the following example:

```
<DFPSlotsProvider collapseEmptyDivs dfpNetworkId={network}>
      ...
      <div>
        <div className="ad-example-728x90">
          <AdSlot sizes={[[728, 90]]} />
        </div>
        <div className="ad-example-300x250">
          <AdSlot sizes={[[300, 250]]} />
        </div>
      </div>
        ...
       <div> ... </div> 
       ....
</DFPSlotsProvider>
```

The googfc console shows the value is set properly:
<img width="1030" alt="screen shot 2017-12-21 at 7 17 40 pm" src="https://user-images.githubusercontent.com/433609/34277275-c6fb8f32-e683-11e7-8f3d-04f3c98bf5db.png">

Can you please give this a try? let me know if u have issues.

Thanks

**Comment by evrenakar** [comment]
Thank you for your reply!
