### ISSUE TITLE
Feature Request - Render Sync and Single Request

### ISSUE THREAD

**Issue by JonatanSalas** [jaanauati/react-dfp#47]
Hey! First of all, thanks for your project! 

I have one question, is there any posibility to be able to add support for `syncRender` and `singleRequest`? Or there is existent support for those? 

Would you be able to accept a PR?

**Comment by jaanauati** [comment]
Hey there, 
regarding 'single request', it is enabled by default (https://github.com/jaanauati/react-dfp/blob/master/js/manager.js#L122), regarding syncRender, i'm really familiar with the feature, is this part of the google dfp/gpt api? 

and yes sure thing!, feel free to fork and send a pull request! just make sure u keep tests and docs up-to-date (npm run test  & Readme file). thanks

**Comment by JonatanSalas** [comment]
Great! I will came back with a PR when implemented!

**Comment by JonatanSalas** [comment]
Hi! I have seen that you have some issues related to features that you want to add to the project, most of them related to infraestructure and dependency updates, would you mind a PR that: 
- Moves the project to a yarn workspace enviroment, so you can add an example app with create-react-app
- Add a doc site backed by [docosaurus](https://docusaurus.io/) with github pages
- Update dependencies and some babel-presets to use spread-operator, decorators, etc. 
- Move the build from grunt to rollup, I have been using rollup for most of my libraries and it's pretty amazing for libraries. 
- Add coverage support with coveralls or codecov, and generate the coverage report from a tool like istanbul or isparta.
- Move the test suite from using react-test-addons to use Jest for snapshot testing or Enzyme.
- I will add support also for sync-rendering.

I have seen that you have a PR of your own #45, and this PR modifies lots of files. If you have intend to add support for adsense, I will wait for you to merge it, and then proceed to work in this PR.

Also, I would like you to create a development branch, so I can offer the PR against development instead of master, so you have time to test it enough when it's really done. 

Well, let me know your thoughts!

**Comment by JonatanSalas** [comment]
I offer all of this stuff because it's a great project, and we've intended to make use of it, in tons of sites from Grupo America.

**Comment by jaanauati** [comment]
hi!, really appreciate your help and feedback, just make sure u submit the new stuff in different pull requests (big pull requests are error prone, and on other hand the smaller the pull request, the easier to review). 

Regarding the development branch, i believe you should be able to create it for your fork.

Thanks!

**Comment by JonatanSalas** [comment]
@jaanauati anyway, the most big pull request will be migrate the project to a yarn workspace. Because It will change all the project structure

**Comment by tomellwood** [comment]
Regarding the above issue where you mention SRA is enabled by default; do you need to disable autoload for this to work?

DFPSlotsProvider looks like it's setup to run DFPManager.load() on 'componentDidMount' before the adSlots have been registered, causing individual network requests for the ads.
