### ISSUE TITLE
enableSingleRequest not working on load

### ISSUE THREAD

**Issue by Matt-Lauderdale** [jaanauati/react-dfp#51]
enableSingleRequest is not enabled on the initial request. I am seeing individual requests for each ad. Subsequent refreshes have single request enabled

```js
import { DFPSlotsProvider, AdSlot } from 'react-dfp';
...
<DFPSlotsProvider dfpNetworkId={'9999'} adUnit={"foo/bar/baz"} >
    <AdSlot sizes={[ [900, 90], [728, 90]]} />
    <AdSlot sizes={[ [300, 250], [300, 600]]} />
</DFPSlotsProvider>
```

**Comment by Matt-Lauderdale** [comment]
It looks like load() is being called for each slot

**Comment by jaanauati** [comment]
https://github.com/jaanauati/react-dfp/pull/53, I still need to test this a bit more though.... will have news in the following 2-3 days.

**Comment by jaanauati** [comment]
@Matt-Lauderdale just pushed v0.7.0 to npm which ships a fix for single-request-mode, can u please give it a try and let me know?
