### ISSUE TITLE
Add className to div rendered in DFPSlotsProvider

### ISSUE THREAD

**Issue by mplis** [jaanauati/react-dfp#52]
For styling purposes, it would be nice to be able to target the `div` that is rendered [here](https://github.com/jaanauati/react-dfp/blob/master/js/dfpslotsprovider.js#L82) more easily.

**Comment by jaanauati** [comment]
Hi, you mean to provide ability to configure arbitrary class names per ad slot?

**Comment by jaanauati** [comment]
@mplis do u still think this is required at all? if so, can u please take a look at my question above???, thanks!

**Comment by scott-thrillist** [comment]
@mplis this has been addressed in v0.15.0 here:

https://github.com/jaanauati/react-dfp/pull/158/files#diff-e22798893a46fa1cfc1f146b9c648cd7R191

Feel free to start using `className` as a prop for `<AdSlot />`
