### ISSUE TITLE
Can control responsive view using sizemapping? 

### ISSUE THREAD

**Issue by enteeee** [jaanauati/react-dfp#55]
I wanted to control responsive view by using sizemapping, something like,

```
export const GOOGLE_ADS_SIZEMAPPING_MEMBER_PROFILE_MOBILE = [
  { viewport: [960, 300], sizes: [[300, 100], [200, 200], [300, 250], [250, 250]] },
];
```

^^ In this i wanna hide ads for viewport larger than 960px.  

Note: I do use CSS to control the responsive view, but the problem is at user level the ads are hidden but the scripts are still loading.

**Comment by jaanauati** [comment]
You should be able to configure the size mappings with the sizeMapping prop: sizeMapping={ [ {viewport: [1024, 768], sizes:[[728, 90], [300, 250]]},
See the docs for reference.
