### ISSUE TITLE
DFP Provider overriding AdSlot Sizes

### ISSUE THREAD

**Issue by LucasKA** [jaanauati/react-dfp#6]
First off, great component! Well designed API and easy to use especially as I'm learning DFP. Works like a react component should.

Here's an issue I'm running into, and I don't know if it's my understanding of the DFP,  or what.

I built an AdUnit component using this, here it is:

```
import React, { PropTypes as PT } from 'react';
import { DFPManager, DFPSlotsProvider, AdSlot } from 'react-dfp';
import Interval from 'react-interval';

const AdUnit = props => (
  <section className={`ad-unit tc ${props.classString}`}>
    <h5 className="p0 ttu sans-serif fw2 mb2">advertisement</h5>
    <Interval
      enabled={props.enableRefresh}
      timeout={props.rate * 1000}
      callback={() => { DFPManager.refresh(); }}
    />
    <DFPSlotsProvider
      dfpNetworkId={props.dfpId}
      targetingArguments={props.targeting}
      sizeMapping={[
        { viewport: [768, 0], sizes: [[728, 90]] },
        { viewport: [0, 0], sizes: [[320, 50], [300, 50]] }]}
    >
      <AdSlot
        dfpNetworkId={props.dfpId}
        adUnit={props.tag}
        sizes={props.sizes}
        shouldRefresh={() => (props.enableRefresh)}
      />
    </DFPSlotsProvider>
  </section>
);

AdUnit.propTypes = {
  tag: PT.string.isRequired,
  targeting: PT.object,
  classString: PT.string,
  dfpId: PT.string.isRequired,
  rate: PT.number,
  sizes: PT.arrayOf(PT.array),
  enableRefresh: PT.bool,
};

AdUnit.defaultProps = {
  dfpId: 'REDACTED',
  rate: 30,
  enableRefresh: false,
  sizes: [[300, 250], [320, 50], [300, 50]],
};

module.exports = AdUnit;
```

So the DFPSlotsProvider defines what sizes of ads can be displayed at what viewport, but the sizes in the AdSlot should show up in that particular slot, correct?

I have overridden my "sizes" in the AdSlot to NOT include [300, 250], but they are still showing up in the AdSlot.

Any ideas why that might be happening?

Regardless, thanks for your help and your work on this great component.

**Comment by jaanauati** [comment]
hey!, are you using your custom ```<AdUnit />``` comp more than once in your app?, b/c i noticed that you are wrapping every ```<DFPSlot/>``` with a new```<DFPSlotsProvider />``` , which is likely creating issues. 

DFPSlotsProvider Is designed to be included only once in your app (wrapping everything):

```
<DFPSlotsProvider>
  ...
 <div>
 <DFPSlot ... />
 ...
 <DFPSlot ... />
  ...
 </div>
 ....
</DFPSlotsProvider>
```

Can you check if this is causing your issues?

thanks!

**Comment by LucasKA** [comment]
I had a feeling this was the issue :)

**Comment by jaanauati** [comment]
🍻

**Comment by LucasKA** [comment]
I don't think this is the issue, I tried wrapping my gallery with DFPSlotsProvider at the top level of the component and am still getting the same issue.

**Comment by LucasKA** [comment]
@jaanauati I hate to bother you about this too much, but I'm not mega familiar with DFP, and this doesn't seem to be working the way that I understood how DFP works.

So from my understanding, `DFPSlotsProvider` is the config for overall ads, with the _SizeMapping_ dictates what size ads are available at different viewport viewport sizes.

The child of the `DFPSlotsProvider`, is the `AdSlot`, which dictates what Ad Tag to display, and what size of ads are allowed in that slot?

Currently, in react-dfp, if I configure my global DFPSlotsProvider to allow `[[300, 250], [320, 50], [300, 50]]` on my mobile resolutions, but set my `AdUnit` to be `[[320, 50], [300, 50]]`, it still allows the [300, 250] to display.

And this is regardless of if `DFPSlotsProvider` is declared multiple times in my code above, or if I pull it out to the top level of the app.


Am I doing something wrong here?
