### ISSUE TITLE
DFPSlotsProvider makes assumptions about child components.

### ISSUE THREAD

**Issue by LucasKA** [jaanauati/react-dfp#7]
When messing with #6 I found that <DFPSlotsProvider /> makes assumptions about it's children. Inside my app I have an array rendered, and the PropTypes of DFPSP throws an error.

**Comment by jaanauati** [comment]
hi!, can you share your code?? thanks!

**Comment by LucasKA** [comment]
Sure

```
  <DFPSlotsProvider
      dfpNetworkId={props.dfpId}
      targetingArguments={props.targeting}
      sizeMapping={[
        { viewport: [768, 0], sizes: [[728, 90]] },
        { viewport: [0, 0], sizes: [[300, 250], [320, 50], [300, 50]] }]}
    >
      {this.renderPhotoArrayWithAds(this.props.images, this.props.adSettings.frequency)}

</DFPSlotsProvider>
```

The proptype validation seems to be failing because the child is an array?

If DFPSlotsProvider is designed to basically be a global wrapper, should it make assumptions on what it's children might be?

**Comment by LucasKA** [comment]
I cleared this up by wrapping my children in a div element. :)
