### ISSUE TITLE
AdUnit size array should accept 'fluid' string too

### ISSUE THREAD

**Issue by MarcosOcf** [jaanauati/react-dfp#8]
Hi! I received this warning using 'fluid' size string on `AdUnit` component.

```
<AdUnit size=['fluid'] {...other} />
```
```
Failed prop type: Invalid prop `sizes[0]` of type `string` supplied to `AdSlot`, expected an array.
```

'fluid' param is described in https://developers.google.com/doubleclick-gpt/reference.

xD

**Comment by jaanauati** [comment]
thanks for reporting this!, 🍻,

https://github.com/jaanauati/react-dfp/pull/9/, 
wanna give it a shot? I'll be merging it away next mon/tues.

thanks again.

**Comment by jaanauati** [comment]
https://github.com/jaanauati/react-dfp/releases/tag/0.3.6
