### ISSUE TITLE
There is no support for Out-Of-Page slots?

### ISSUE THREAD

**Issue by anton-asnitsky** [jaanauati/react-dfp#80]
Hi there. For some reason I've did not found no explanation how to create OutOfPage slots. Does this feature supported?

**Comment by jonatananauati-natgeo** [comment]
@anton-asnitsky  do u still need help w this topic? here an example: please thttp://react-dfp.tk/adslot/renderoutofthepage/.

**Comment by jaanauati** [comment]
@anton-asnitsky do u still need help w this topic? here an example: please thttp://react-dfp.tk/adslot/renderoutofthepage/
