### ISSUE TITLE
Consider deleting examples directory from published package

### ISSUE THREAD

**Issue by leinelissen** [jaanauati/react-dfp#85]
Hey there! 

I was just doing an audit of our Node project. Please consider deleting the examples directory when publishing, or only publishing a subset of the files in this repo. The examples directory adds 10MB no-one installing this package will ever use.

![screen shot 2018-11-27 at 3 33 56 pm](https://user-images.githubusercontent.com/10154841/49058890-16e6c100-f25a-11e8-9031-109de82ed6a7.png)

**Comment by jaanauati** [comment]
@leinelissen thank you for bringing this, I've already made a tweak to the package config, the `examples` directory is no longer getting pushed.

```
➜  reactdfp git:(master) ✗ ls -ltr node_modules/react-dfp
total 48
-rw-r--r--  1 jonatan  staff    792 26 oct  1985 karma.conf.js
-rw-r--r--  1 jonatan  staff  11239 26 oct  1985 Readme.md
-rw-r--r--  1 jonatan  staff   1087 26 oct  1985 LICENSE
drwxr-xr-x  7 jonatan  staff    224 29 dic 00:55 js
drwxr-xr-x  7 jonatan  staff    224 29 dic 00:55 lib
drwxr-xr-x  5 jonatan  staff    160 29 dic 00:55 spec
-rw-r--r--  1 jonatan  staff   3859 29 dic 00:55 package.json
```
Please give it a shot and let me know if u find issues.

Thanks.
