### ISSUE TITLE
Disable SingleRequest mode

### ISSUE THREAD

**Issue by shotap** [jaanauati/react-dfp#90]
Hi, is there any way to disable SingleRequest mode?

**Comment by jaanauati** [comment]
umm, nope, but I guess that just adding a new prop and a conditional surrounding the following line should do it:
https://github.com/jaanauati/react-dfp/blob/master/js/manager.js#L200

if time allows me, I will try to push a tweak in the following days.

thanks.

**Comment by jaanauati** [comment]
ok, I've just made the updates to the api, example:
```
            <DFPSlotsProvider singleRequest={false} dfpNetworkId='9999'>
                <div className="desktop-ads">
                    <AdSlot sizes={[[728,90], [300, 250]]} adUnit='homepage/1' />
                </div>
                <div className="mobile-ads">
                    <AdSlot sizes={[[320,50], [300, 50]]} adUnit='homepage/mobile' />
                </div>
            </DFPSlotsProvider
```
- new property: singleRequest.
- default: true.

please give it a try and let me know if it works for u.

thanks.

**Comment by shotap** [comment]
looks great!
