### ISSUE TITLE
Feature Request - setRequestNonPersonalizedAds

### ISSUE THREAD

**Issue by vandal777** [jaanauati/react-dfp#95]
Hi. With the new European data protection law, I have needed to make some adjustments with the advertising sample depending on the acceptance of consent. You could add an attribute to control custom ads.

Thanks for your work, it has helped me a lot with my project.

**Comment by jaanauati** [comment]
@vandal777 I've published v0.9.0 yesterday, this version adds the prop `personalizedAds` to the DFPAdsProvider.
```
            <DFPSlotsProvider personalizedAds={false} dfpNetworkId='9999'>
                ....
                <div>
                    <AdSlot sizes={[[728,90], [300, 250]]} adUnit='homepage/1' />
                </div>
                  .....
                <div>
                    <AdSlot sizes={[[320,50], [300, 50]]} adUnit='homepage/mobile' />
                </div>
                ...
            </DFPSlotsProvider>
```

I also added the method configurePersonalizedAds to the DFPManager, (DFPManager. configurePersonalizedAds(false) --> disable ads), so you could also use this one method in case that you don't use the DFPSlotsProvider component.

please have a look and let me know if u find issues.

**Comment by vandal777** [comment]
looks great !! thanks man !!
Do you know how I can check this feature is running well?
There are some parameter on the header request of this ads like "correlator" or "prev_scp".

**Comment by jaanauati** [comment]
i'm sorry, I had missed this question,  

have you finally found a way to check this?,

On my side, when worked on this code, I noticed that, unfortunately, the google gpt console (?googfc) does not show any kind of information about this configuration when passing expected values (1 or 0) via setRequestNonPersonalizedAds().

On the other hand, I did notice that it does show error messages in the debugging tab when passing incorrect values (example: setRequestNonPersonalizedAds(42)), so this was the only way i found to test that my code is running.

Hope it helps,
thanks.

**Comment by vandal777** [comment]
Hi jaanauati! No problem.

I have not found the correct way to perform the test, to what I have done an act of faith.
I have followed the googletag documentation and your code is correct. Maybe someday they add the attribute in the dfp console for check this nonPersonalized.

Thx for all man, you help me a lot with this project !
